# Generated by Django 4.1.7 on 2023-03-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cards',
            options={'verbose_name': 'Card', 'verbose_name_plural': 'Cards'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='date_time',
            new_name='movement_date',
        ),
        migrations.AlterField(
            model_name='cards',
            name='is_costcenter',
            field=models.BooleanField(default=False),
        ),
    ]
