# Generated by Django 5.0.3 on 2024-09-22 11:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_id', models.BigIntegerField(editable=False, unique=True)),
                ('establecimiento', models.CharField(max_length=30)),
                ('importe', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('consumo_date', models.DateTimeField(auto_now_add=True)),
                ('tipo_combustible', models.CharField(max_length=30)),
                ('odometro', models.FloatField()),
                ('rubro', models.CharField(max_length=30)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costcenter.cards')),
            ],
            options={
                'verbose_name': 'Consumo',
                'verbose_name_plural': 'Consumos',
            },
        ),
    ]
