# Generated by Django 5.0.3 on 2024-09-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcenter', '0002_consumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='id',
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
