# Generated by Django 5.0.3 on 2024-11-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcenter', '0004_remove_consumo_id_alter_consumo_consumo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo',
            name='id',
            field=models.BigAutoField(auto_created=True, default=888888888, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consumo',
            name='consumo_id',
            field=models.BigIntegerField(editable=False, unique=True),
        ),
    ]
