# Generated by Django 5.0.3 on 2024-11-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcenter', '0005_consumo_id_alter_consumo_consumo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumo',
            name='id',
        ),
        migrations.AddField(
            model_name='cards',
            name='unit',
            field=models.CharField(default=5, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consumo',
            name='consumo_id',
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
