# Generated by Django 5.0.3 on 2024-11-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcenter', '0007_remove_cards_unit_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumo',
            name='tipo_combustible',
        ),
        migrations.AddField(
            model_name='consumo',
            name='cantidad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumo',
            name='clase',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='consumo',
            name='monto_parcial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumo',
            name='nro_factura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumo',
            name='nro_movil',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumo',
            name='tipo_de_gasto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='consumo',
            name='un_med',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='consumo_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='odometro',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
