# Generated by Django 5.0.3 on 2024-11-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcenter', '0008_remove_consumo_tipo_combustible_consumo_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo',
            name='num_ticket',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
