# Generated by Django 5.0.3 on 2024-11-15 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcenter', '0009_consumo_num_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='clase',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='tipo_de_gasto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='un_med',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from+', to='costcenter.cards'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to+', to='costcenter.cards'),
        ),
    ]
