# Generated by Django 5.0.3 on 2024-11-16 18:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcenter', '0011_userprofile_user_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='card_name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Acreditaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('numero', models.BigIntegerField(editable=False, unique=True)),
                ('observaciones', models.CharField(max_length=50)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('card', models.ForeignKey(limit_choices_to={'is_costcenter': True}, on_delete=django.db.models.deletion.CASCADE, related_name='acreditaciones', to='costcenter.cards')),
            ],
            options={
                'verbose_name': 'Acreditación',
                'verbose_name_plural': 'Acreditaciones',
            },
        ),
    ]
