# Generated by Django 5.0.3 on 2024-11-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcenter', '0012_alter_cards_card_name_acreditaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acreditaciones',
            name='numero',
        ),
        migrations.AlterField(
            model_name='acreditaciones',
            name='id',
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
